function Reformaes(){
	return(
	<div>
<p>

1- Eliminación y reducción gradual de Impuestos.
2- Reforma de la administración nacional
3- Reducción progresiva hasta la eliminación de los subsidios a la energía y al transporte .
5- Reducción gradual de planes sociales
6- Reforma laboral
7- Reforma de la Coparticipación Federal
8- Apertura externa
9- Desregulación y simplificación normativa
10- Fortalecimiento y respaldo de la moneda
Las medidas 2 a 5 apuntan a lograr superávit fiscal genuino que permita disminuir la presión impositiva y disipe totalmente la presunción de un futuro default. Ese logro, acompañado del resto de las medidas constituirán el eje del programa para recuperar la confianza y la inversión, asegurar la estabilidad y reducir genuinamente las tasas de interés y expandir el crédito. Estas medidas económicas deberán acompañarse por la consolidación de una justicia eficiente e independiente, por mejor seguridad y por estabilidad política. Así se impulsará la inversión, la competitividad y la creación de empleo privado. Esto último hará factible la reducción del empleo público y de los subsidios sociales. De esa manera el actual círculo vicioso de estancamiento, déficit e inflación, se convertirá en el círculo virtuoso del crecimiento, el empleo, el mejoramiento del salario real y la estabilidad.
1 – Eliminación y reducción gradual de impuestos: Revisión integral de la estructura tributaria a fin de suprimir gravámenes de muy escasa recaudación, reducir su peso y simplificar su administración por parte de los contribuyentes. Es imposible pensar que alguien invertirá en un país que está en el 2º puesto, entre 190, en un ranking de los que más exprimen a sus empresas con impuestos o, según el Banco Mundial, una PyMe que pagará todos sus tributos es altamente probable que pierda plata. Por supuesto, sería demagógico plantear esto sin aclarar que demandará hacer más eficiente el gasto público para llevarlo a niveles que sean pagables con una imposición razonable.
2 – Reforma de la administración nacional: Su objetivo es reducir sustancialmente el número de empleados de la Administración Nacional y las erogaciones innecesarias, asegurando que ninguna persona pierda ingresos en lo inmediato y que tenga oportunidad de reinsertarse y progresar. Comprende: i) Cambios en las normas laborales del sector público para incorporar la gestión por resultados. Continuar con la digitalización y las mejoras en la tecnología informática. ii) un Decreto con nueva estructura (hay un organigrama propuesto) en el marco de las atribuciones establecidas en la Ley 25.164, de Empleo Público. Se definirán las unidades administrativas dependientes de cada uno de los ocho ministerios, hasta el nivel de direcciones nacionales, direcciones generales y organismos descentralizados. El decreto establecerá la dotación de personal de cada unidad administrativa, por categoría. iii) Designación de los ministros de la nueva estructura. En forma transitoria, por 90 días, las unidades administrativas de la vieja estructura son asignadas a cada uno de los nuevos ministerios. En ese plazo cada nuevo ministro cubre los cargos de la nueva estructura dando prioridad al personal en disponibilidad. Una vez completado el re encasillamiento del personal, los que no hubieran sido reubicados en la nueva estructura quedarán en la condición de disponibilidad establecida por la Ley N° 25.164 Art 11 (No cumplen tareas; pero cobran un sueldo por uno o dos años. Así se evita el costo social de que queden sin ingresos.). iv) Incentivos a las empresas que los contraten: ej: eximición de los aportes patronales durante un período de dos años y subsidio sobre los gastos de capacitación en el nuevo empleo. Jubilación temprana a quienes, quedando en disponibilidad, no hubieran conseguido empleo en dos años y tengan más de 60 años de edad.
3 – Reducción hasta la eliminación de los subsidios a la energía y al transporte, en un plazo prudencial las tarifas y precios, para que cubran los costos más una ganancia que incentive la inversión en el sector. El impacto sobre los estratos de menores ingresos deberá amortiguarse selectivamente con instrumentos de subsidio a la demanda (Tarifa Social).
5 – Reducción gradual de planes sociales a quienes menos los necesiten e incentivando al sector productivo a darles empleo, por ejemplo, generalizando el plan “Empalme”. Auditoría internacional para revisar los excesos cometidos en la asignación fraudulenta de las prestaciones por invalidez. La idea de fondo de nuestra propuesta es que “El mejor plan es un trabajo productivo digno”; por lo que es fundamental incentivar la creación de empleo productivo. No sólo para los que hoy reciben planes, sino también para aquellos que tienen un trabajo en el Estado que no es útil para la sociedad. El problema es que, aunque se creen las condiciones para aumentar la inversión, la actual legislación laboral desincentiva la creación de puestos laborales en el sector privado.
6 – Reforma laboral. Privilegiar los acuerdos laborales a nivel de empresa sobre los acuerdos colectivos a nivel de sector de actividad. Ello requerirá que se unifique la representación de los trabajadores de la empresa. Esta reforma requiere un cambio en los artículos 17, 18 y 19 de la Ley 14.250 de Convenciones Colectivas (por DNU o por Ley). Asegurar la libertad sindical. Desregular y simplificar los controles administrativos de la autoridad de aplicación, y de la policía laboral. Modificar mediante decreto reglamentario, el Art 84 de la Ley de Contrato de Trabajo para aumentar la productividad y reducir el sobrecosto y el riesgo laboral. Reducir el costo y riesgo de despido, respetando los derechos adquiridos, mediante la supresión hacia adelante de la indemnización por despido (reforma de los artículos 231 a 255 de la Ley de Contrato de Trabajo, por DNU o Ley) compensado por un fondo y seguro de desempleo. Otra opción es el sistema aplicado en Austria, conocido como “mochila austríaca”.
7 – Reforma de la Coparticipación Federal. Contempla el envío al Congreso de una Ley para la devolución de potestades tributarias a las provincias (Ganancias de personas físicas, Combustibles, Bienes Personales, Internos). Reemplazo de Ingresos Brutos por Ventas (son provinciales) y calibración de éste con la alícuota del IVA (nacional) para empalmar con la distribución primaria vigente. Supresión de la coparticipación vertical. Compatibilidad con actual distribución secundaria mediante un Fondo de redistribución horizontal que produzca un empalme con sistema vigente, pero que al quedar inamovibles esos porcentajes exija acompañar cualquier aumento de gasto de una provincia, con impuestos provinciales adicionales. De esa forma se alinearán los incentivos y se propenderá a gastar menos y mejor.
8 – Apertura externa. Acompañar a los socios del Mercosur en la concreción de acuerdos de libre comercio. Acordar en el Mercosur la forma de reducción del arancel externo común y eliminar definitivamente las aduanas entre los países socios. El proteccionismo pone a los consumidores en función de las ganancias de los empresarios privilegiados; lo cual es injusto. La apertura los obliga a competir para obtener rendimientos, incentivándolos a brindar productos y servicios de mayor calidad al menor precio; lo que redunda en mayor bienestar para la gente.
9 – Desregulación y simplificación normativa. Particularmente de las normas de la AFIP, del BCRA y de otros organismos regulatorios. Hoy hay más de 67.000 regulaciones que asfixian particularmente a emprendedores y PyMes. Desandar las normas intervencionistas (Ej. Ley de Alquileres). Facilitar el uso de dinero electrónico.
10 – Fortalecimiento y respaldo de la moneda: Una alternativa posible es, luego que se restablezca el nivel de las reservas, que podrán reforzarse con un swap o un préstamo sólo utilizable como respaldo, y cuando alcancen el nivel de la base monetaria al tipo de cambio libre vigente, se establecerá la convertibilidad peso-dólar. A diferencia de la que se implementó entre 1992 y 2001, a fin de garantizar su mantenimiento en el tiempo, el depositario de las reservas asignadas a la convertibilidad y su manejo, debería ser una institución financiera internacional (Ej: Banco de Ajustes de Basilea)


</p>

<p>

Las medidas 2 a 5 apuntan a lograr superávit fiscal genuino que permita disminuir la presión impositiva y disipe totalmente la presunción de un futuro default. Ese logro, acompañado del resto de las medidas constituirán el eje del programa para recuperar la confianza y la inversión, asegurar la estabilidad y reducir genuinamente las tasas de interés y expandir el crédito. Estas medidas económicas deberán acompañarse por la consolidación de una justicia eficiente e independiente, por mejor seguridad y por estabilidad política. Así se impulsará la inversión, la competitividad y la creación de empleo privado. Esto último hará factible la reducción del empleo público y de los subsidios sociales. De esa manera el actual círculo vicioso de estancamiento, déficit e inflación, se convertirá en el círculo virtuoso del crecimiento, el empleo, el mejoramiento del salario real y la estabilidad.
1 – Eliminación y reducción gradual de impuestos: Revisión integral de la estructura tributaria a fin de suprimir gravámenes de muy escasa recaudación, reducir su peso y simplificar su administración por parte de los contribuyentes. Es imposible pensar que alguien invertirá en un país que está en el 2º puesto, entre 190, en un ranking de los que más exprimen a sus empresas con impuestos o, según el Banco Mundial, una PyMe que pagará todos sus tributos es altamente probable que pierda plata. Por supuesto, sería demagógico plantear esto sin aclarar que demandará hacer más eficiente el gasto público para llevarlo a niveles que sean pagables con una imposición razonable.
2 – Reforma de la administración nacional: Su objetivo es reducir sustancialmente el número de empleados de la Administración Nacional y las erogaciones innecesarias, asegurando que ninguna persona pierda ingresos en lo inmediato y que tenga oportunidad de reinsertarse y progresar. Comprende: i) Cambios en las normas laborales del sector público para incorporar la gestión por resultados. Continuar con la digitalización y las mejoras en la tecnología informática. ii) un Decreto con nueva estructura (hay un organigrama propuesto) en el marco de las atribuciones establecidas en la Ley 25.164, de Empleo Público. Se definirán las unidades administrativas dependientes de cada uno de los ocho ministerios, hasta el nivel de direcciones nacionales, direcciones generales y organismos descentralizados. El decreto establecerá la dotación de personal de cada unidad administrativa, por categoría. iii) Designación de los ministros de la nueva estructura. En forma transitoria, por 90 días, las unidades administrativas de la vieja estructura son asignadas a cada uno de los nuevos ministerios. En ese plazo cada nuevo ministro cubre los cargos de la nueva estructura dando prioridad al personal en disponibilidad. Una vez completado el re encasillamiento del personal, los que no hubieran sido reubicados en la nueva estructura quedarán en la condición de disponibilidad establecida por la Ley N° 25.164 Art 11 (No cumplen tareas; pero cobran un sueldo por uno o dos años. Así se evita el costo social de que queden sin ingresos.). iv) Incentivos a las empresas que los contraten: ej: eximición de los aportes patronales durante un período de dos años y subsidio sobre los gastos de capacitación en el nuevo empleo. Jubilación temprana a quienes, quedando en disponibilidad, no hubieran conseguido empleo en dos años y tengan más de 60 años de edad.
3 – Reducción hasta la eliminación de los subsidios a la energía y al transporte, en un plazo prudencial las tarifas y precios, para que cubran los costos más una ganancia que incentive la inversión en el sector. El impacto sobre los estratos de menores ingresos deberá amortiguarse selectivamente con instrumentos de subsidio a la demanda (Tarifa Social).
5 – Reducción gradual de planes sociales a quienes menos los necesiten e incentivando al sector productivo a darles empleo, por ejemplo, generalizando el plan “Empalme”. Auditoría internacional para revisar los excesos cometidos en la asignación fraudulenta de las prestaciones por invalidez. La idea de fondo de nuestra propuesta es que “El mejor plan es un trabajo productivo digno”; por lo que es fundamental incentivar la creación de empleo productivo. No sólo para los que hoy reciben planes, sino también para aquellos que tienen un trabajo en el Estado que no es útil para la sociedad. El problema es que, aunque se creen las condiciones para aumentar la inversión, la actual legislación laboral desincentiva la creación de puestos laborales en el sector privado.
6 – Reforma laboral. Privilegiar los acuerdos laborales a nivel de empresa sobre los acuerdos colectivos a nivel de sector de actividad. Ello requerirá que se unifique la representación de los trabajadores de la empresa. Esta reforma requiere un cambio en los artículos 17, 18 y 19 de la Ley 14.250 de Convenciones Colectivas (por DNU o por Ley). Asegurar la libertad sindical. Desregular y simplificar los controles administrativos de la autoridad de aplicación, y de la policía laboral. Modificar mediante decreto reglamentario, el Art 84 de la Ley de Contrato de Trabajo para aumentar la productividad y reducir el sobrecosto y el riesgo laboral. Reducir el costo y riesgo de despido, respetando los derechos adquiridos, mediante la supresión hacia adelante de la indemnización por despido (reforma de los artículos 231 a 255 de la Ley de Contrato de Trabajo, por DNU o Ley) compensado por un fondo y seguro de desempleo. Otra opción es el sistema aplicado en Austria, conocido como “mochila austríaca”.
7 – Reforma de la Coparticipación Federal. Contempla el envío al Congreso de una Ley para la devolución de potestades tributarias a las provincias (Ganancias de personas físicas, Combustibles, Bienes Personales, Internos). Reemplazo de Ingresos Brutos por Ventas (son provinciales) y calibración de éste con la alícuota del IVA (nacional) para empalmar con la distribución primaria vigente. Supresión de la coparticipación vertical. Compatibilidad con actual distribución secundaria mediante un Fondo de redistribución horizontal que produzca un empalme con sistema vigente, pero que al quedar inamovibles esos porcentajes exija acompañar cualquier aumento de gasto de una provincia, con impuestos provinciales adicionales. De esa forma se alinearán los incentivos y se propenderá a gastar menos y mejor.
8 – Apertura externa. Acompañar a los socios del Mercosur en la concreción de acuerdos de libre comercio. Acordar en el Mercosur la forma de reducción del arancel externo común y eliminar definitivamente las aduanas entre los países socios. El proteccionismo pone a los consumidores en función de las ganancias de los empresarios privilegiados; lo cual es injusto. La apertura los obliga a competir para obtener rendimientos, incentivándolos a brindar productos y servicios de mayor calidad al menor precio; lo que redunda en mayor bienestar para la gente.
9 – Desregulación y simplificación normativa. Particularmente de las normas de la AFIP, del BCRA y de otros organismos regulatorios. Hoy hay más de 67.000 regulaciones que asfixian particularmente a emprendedores y PyMes. Desandar las normas intervencionistas (Ej. Ley de Alquileres). Facilitar el uso de dinero electrónico.
10 – Fortalecimiento y respaldo de la moneda: Una alternativa posible es, luego que se restablezca el nivel de las reservas, que podrán reforzarse con un swap o un préstamo sólo utilizable como respaldo, y cuando alcancen el nivel de la base monetaria al tipo de cambio libre vigente, se establecerá la convertibilidad peso-dólar. A diferencia de la que se implementó entre 1992 y 2001, a fin de garantizar su mantenimiento en el tiempo, el depositario de las reservas asignadas a la convertibilidad y su manejo, debería ser una institución financiera internacional (Ej: Banco de Ajustes de Basilea)


</p>

</div>
)
}


export default Reformaes